import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-retail-media-network-spend-reconciliation",
  "engine": "recovery",
  "title": "Retail Media Network Spend Reconciliation",
  "shortTitle": "Retail Media Network Spend Reconciliation",
  "tagline": "Audit retail-media delivery, pricing, attribution, budget, and makegood credits across retailer networks.",
  "industry": "Retail Media Cost Assurance",
  "buyer": "Consumer brands and retail media buyers",
  "uiPort": 4729,
  "apiPort": 5729,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Retail Media Network Spend Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits in one accountable workflow. Audit retail-media delivery, pricing, attribution, budget, and makegood credits across retailer networks.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Retail Media Network Spend Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("retail-media-agreement-library","RMN01","Retail media agreement library","Execute retail media agreement library using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed retail media agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Retail media agreement library Reference","text","RMN01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("campaign-order-ingestion","RMN02","Campaign order ingestion","Execute campaign order ingestion using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed campaign order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Campaign order ingestion Reference","text","RMN02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("audience-targeting-evidence","RMN03","Audience targeting evidence","Execute audience targeting evidence using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed audience targeting evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Audience targeting evidence Reference","text","RMN03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("impression-delivery-validation","RMN04","Impression delivery validation","Execute impression delivery validation using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed impression delivery validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Impression delivery validation Reference","text","RMN04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("click-event-reconciliation","RMN05","Click event reconciliation","Execute click event reconciliation using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed click event reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Click event reconciliation Reference","text","RMN05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("rate-card-calculation","RMN06","Rate card calculation","Execute rate card calculation using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed rate card calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Rate card calculation Reference","text","RMN06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("budget-pacing-control","RMN07","Budget pacing control","Execute budget pacing control using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed budget pacing control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Budget pacing control Reference","text","RMN07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("attributed-sales-methodology","RMN08","Attributed sales methodology","Execute attributed sales methodology using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed attributed sales methodology decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Attributed sales methodology Reference","text","RMN08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("incrementality-evidence","RMN09","Incrementality evidence","Execute incrementality evidence using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed incrementality evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Incrementality evidence Reference","text","RMN09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("invalid-traffic-adjustment","RMN10","Invalid traffic adjustment","Execute invalid traffic adjustment using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed invalid traffic adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Invalid traffic adjustment Reference","text","RMN10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("under-delivery-makegood","RMN11","Under-delivery makegood","Execute under-delivery makegood using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed under-delivery makegood decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Under-delivery makegood Reference","text","RMN11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("invoice-campaign-matching","RMN12","Invoice campaign matching","Execute invoice campaign matching using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed invoice campaign matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Invoice campaign matching Reference","text","RMN12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("retailer-dispute-workflow","RMN13","Retailer dispute workflow","Execute retailer dispute workflow using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed retailer dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Retailer dispute workflow Reference","text","RMN13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("credit-reconciliation","RMN14","Credit reconciliation","Execute credit reconciliation using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Credit reconciliation Reference","text","RMN14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]}),
feature("network-campaign-analytics","RMN15","Network campaign analytics","Execute network campaign analytics using media agreements, campaigns, audiences, impressions, clicks, attributed sales, rate cards, budgets, makegoods, invoices, and credits.","Produce a governed network campaign analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Retailer / Campaign","text","Retailer / Campaign · Standard Case"],["caseReference","Network campaign analytics Reference","text","RMN15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1690000],["supportedAmount","Evidence-Supported Amount","currency",1419600],["domainDriver","Media Format","select","Sponsored search",["Sponsored search","Display","Offsite media"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Retail media agreement library case","Campaign order ingestion case","Audience targeting evidence case","Impression delivery validation case","Click event reconciliation case"]})
]);
